version: '3'
services:
   webserver:
      image: nginx:latest
      ports:
         - "80:80"
      volumes:
         - ./web/:/var/www/
         - ./docker/nginx.conf/:/etc/nginx/conf.d/
      networks:
         - web
      depends_on:
         - app
   app:
      build:
         context: ./docker
         dockerfile: dockerfile
      volumes:
         - ./web/:/var/www
      networks:
         - web
networks:
   web:
      driver: bridge
