<?php

namespace ContainerEDJnDyx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDownloadAssetControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DownloadAssetController' shared autowired service.
     *
     * @return \App\Controller\DownloadAssetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/DownloadAssetController.php';

        $container->services['App\\Controller\\DownloadAssetController'] = $instance = new \App\Controller\DownloadAssetController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\DownloadAssetController', $container));

        return $instance;
    }
}
